run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  modules-download-mode: mod
  tests: true
linters:
  disable-all: true
  enable:
    - deadcode
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - revive
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - asciicheck
linters-settings:
  dupl:
    threshold: 1000
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 25
